# Generated by Django 3.1.7 on 2021-03-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='readpage',
            field=models.IntegerField(default=0, verbose_name='しおり'),
        ),
    ]
