# Generated by Django 3.1.7 on 2021-03-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_auto_20210305_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='photo',
            field=models.ImageField(default='defaults/noImage.jpg', upload_to='', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='readpage',
            field=models.CharField(default=0, max_length=100, verbose_name='しおり'),
        ),
    ]
