# Generated by Django 3.1.7 on 2021-03-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_auto_20210307_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='photo',
            field=models.ImageField(default='defaults/noImage.jpg', upload_to='', verbose_name='写真'),
        ),
    ]
