# Generated by Django 3.1.7 on 2021-03-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_auto_20210307_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='readpage',
            field=models.CharField(default='0ページ', max_length=100, verbose_name='しおり'),
        ),
    ]
